---
title: "Calculation of population sensitivity"
author: "Koya Hashimoto"
date: "2024/6/14"
output: 
  html_document: 
    code_folding: hide
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load required packages
  
```{r packages}
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(RColorBrewer)
library(ggsci)
library(glmmTMB)
library(visreg)
library(ggeffects)
library(lme4)
library(car)
library(emmeans)
library(afex)
```

## Data compilation

```{r data compile}

# Load standardized time series

all_Ts <- read.csv("./processed_data/all_Ts240123.csv") 

all_Ts <- #必要な列の作成
  all_Ts %>%
  separate(Year_Tank, into=c("Year", "Tank"), sep="_") %>% #年とタンク
  mutate(Treatment=substr(Tank, 1, nchar(Tank)-1)) %>% #処理名
  mutate(Treatment=factor(Treatment, levels=c("Cont", "Fipro", "Pent", "Joint")), #処理名の順序
         Tank=factor(Tank, levels=unique(Tank)), #タンクの順序
         Recipient=factor(Recipient, levels=c("Phytopla1", "Roti1", "Zoopla1", "Mp1", 
                                              "Det1", "Herb1", "Pred.P1", "Pred.B1", "Pred.S1", "Moll1"))) 

# Visualize data

labeli <- as_labeller(c(`Phytopla1`="Phytoplankton", #facetラベルの付け替え
                        `Roti1`="Rotifers",
                        `Zoopla1`="Crustacean\nzooplankton",
                        `Mp1`="Macrophytes",
                        `Det1`="Detritivores",
                        `Herb1`="Herbivores",
                        `Pred.P1`="Phytophilous\npredators",
                        `Pred.B1`="Benthic\npredators",
                        `Pred.S1`="Neustonic\npredators",
                        `Moll1`="Molluscs"))
lab <- data.frame(lab="*", 
                  Recipient=factor(c("Phytopla1", "Mp1", "Mp1", 
                                 "Herb1", "Pred.P1", "Pred.P1", 
                                 "Pred.B1", "Pred.B1", "Moll1"), 
                               levels=c("Phytopla1", "Roti1", "Zoopla1", "Mp1", 
                                        "Det1", "Herb1", "Pred.P1", "Pred.B1", "Pred.S1", "Moll1")))

palSet1 <- brewer.pal(9, "Set1")

theme_custom <- function() {
  theme_bw() + 
    theme(axis.text=element_text(colour="black"), 
          axis.ticks=element_line(colour="black"),
          panel.border=element_rect(fill=NA, 
                                    colour="black"), 
          panel.spacing=unit(3, "pt"),
          strip.text=element_text(colour="black", lineheight=0.7))
}

set.seed(1)
density.boxplot_gg <- 
  ggplot(na.omit(filter(all_Ts, Recipient!="Pred.C1")), mapping=aes(x=Treatment, y=scAbundance)) +
  geom_boxplot(mapping=aes(fill=Treatment), outlier.shape=NA, size=0.3, colour="black") + 
  scale_fill_manual(values=palSet1[c(9, 1, 2, 3)]) + #塗りの色
  geom_jitter(width=0.2, size=0.1) + 
  facet_wrap(~Recipient, nrow=2, labeller=labeli) + #facetラベル"labeli"
  scale_x_discrete(labels=c("C", "I", "H", "I+H")) + #処理ラベル
  theme_custom() + #theme
  theme(strip.background=element_blank(), legend.position="none") +
  geom_text(data=lab, aes(label=lab), x=c(4, 3, 4, 4, 2, 4, 2, 4, 4), y=2.5, size=10) +
  labs(y="Standardized density") #軸ラベル

density.boxplot_gg # Fig. 2a
```

# Calculation of population sensitivity

```{r calc sensitiivty}

# Averaging density over replicates

all_Ts_smrz <- 
  all_Ts %>%
  group_by(Treatment, Recipient, Year) %>%
  summarise(Abundance_m=mean(Abundance, na.rm=TRUE), #密度生値の平均 raw density
            scAbundance_m=mean(scAbundance, na.rm=TRUE)) #対数変換→標準化後の密度の平均 standardized density (unnesessary)

## `summarise()` regrouping output by 'Treatment', 'Recipient' (override with
## `.groups` argument)

## Show data sheet

head(all_Ts_smrz) # ここでは、タンクは考慮していない(処理間の変化が関心の中心なので)

# Calculating log response ratio

Abundance_TrEff_nRR_0.1 <-  #密度変化をlog response ratioで計算(密度生値) Martinson and Raupp 2013にしたがって、+0.1を入れてみた
  all_Ts_smrz %>%
  ungroup(.) %>%
  select(-scAbundance_m) %>%
  spread(value=Abundance_m, key=Treatment) %>%
  mutate(Fipro_Cont=log((Fipro+0.1)/(Cont+0.1)), 
         Pent_Cont=log((Pent+0.1)/(Cont+0.1)),
         Joint_Cont=log((Joint+0.1)/(Cont+0.1))) %>%
  select(-Cont, -Fipro, -Pent, -Joint) %>%
  gather(key=Treatment_Cont, value=Abundance_response_nRR_0.1, -(1:2)) %>%
  mutate(Treatment_Cont=factor(Treatment_Cont, levels=c("Fipro_Cont", "Pent_Cont", "Joint_Cont")))

Abundance_TrEff <- Abundance_TrEff_nRR_0.1
Abundance_TrEff <- filter(Abundance_TrEff, Recipient!="Pred.C1") #水柱を泳ぐ捕食者を除く
Abundance_TrEff$abs_Abundance_response_nRR_0.1 <- abs(Abundance_TrEff$Abundance_response_nRR_0.1) #Absolute values

Abundance_TrEff$Recipient <- factor(Abundance_TrEff$Recipient, 
                                    levels=c("Phytopla1", "Roti1", "Zoopla1", "Mp1", 
                                             "Det1", "Herb1", "Pred.P1", "Pred.B1", "Pred.S1", "Moll1"))

## Show data sheet

head(Abundance_TrEff)

# Visualize sensitivity

smrz_Abundance_TrEff <- 
  Abundance_TrEff %>%
  group_by(Recipient, Treatment_Cont) %>%
  summarise(abs_Abundance_response_nRR_0.1=(exp(mean(log(abs_Abundance_response_nRR_0.1+1)))-1)) %>% #calculating geometric mean
  ungroup(.)

theme_set(theme_bw())

## Split by functional groups

smrz_Abundance_TrEff %>%
#  mutate(Treatment_Cont=factor(Treatment_Cont, levels=c("Fipro_Cont", "Joint_Cont", "Pent_Cont"))) %>%
  ggplot(aes(x=Treatment_Cont, y=log(abs_Abundance_response_nRR_0.1+1), group=Recipient, color=Recipient)) +
  geom_point(size=2) +
  geom_line() +
  geom_point(Abundance_TrEff, mapping=aes(x=Treatment_Cont, y=log(abs_Abundance_response_nRR_0.1+1), group=Recipient, color=Recipient), alpha=0.2) +
  scale_color_manual(values=(pal_d3(palette="category10")(10))) + 
  guides(color=guide_legend(title=NULL)) +
  ylab("ln(Population sensitivity + 1)")

## Split by treatments

palSet1 <- brewer.pal(9, "Set1")
reaction.norm <-
  smrz_Abundance_TrEff %>%
  #  mutate(Treatment_Cont=factor(Treatment_Cont, levels=c("Fipro_Cont", "Joint_Cont", "Pent_Cont"))) %>%
  ggplot(aes(x=Recipient, y=log(abs_Abundance_response_nRR_0.1+1))) +
  geom_point(aes(group=Treatment_Cont, color=Treatment_Cont), size=4, shape=16) +
  geom_line(aes(, group=Treatment_Cont, color=Treatment_Cont)) +
  geom_point(Abundance_TrEff, mapping=aes(x=Recipient, y=log(abs_Abundance_response_nRR_0.1+1), group=Treatment_Cont, color=Treatment_Cont), alpha=0.4, shape=16) +
  scale_color_manual(values=palSet1[c(1, 2, 3)], labels=c("I vs. C", "H vs. C", "I+H vs. C")) + 
  scale_x_discrete(name="Community member", labels=c("Phyt", "Roti", "C.zoop", "Macr", "Detr", "Herb", "P.pred", "B.pred", "N.pred", "Moll")) + 
  guides(color=guide_legend(title=NULL)) +
  ylab("ln(Population sensitivity + 1)") + 
  theme_custom()

reaction.norm #Fig. 2b

# Statistical analysis

Abundance_TrEff$ln_abs_Abundance_response_nRR_0.1 <- log(Abundance_TrEff$abs_Abundance_response_nRR_0.1 + 1)
m <- lmer(ln_abs_Abundance_response_nRR_0.1 ~ Treatment_Cont * Recipient + (1|Year), Abundance_TrEff)
Anova(m, test="F")

pairs(emmeans(m, specs="Treatment_Cont"))
multcomp::cld(emmeans(m, specs="Recipient"))

plot(ggemmeans(m, terms=c("Recipient", "Treatment_Cont")), connect=TRUE, rawdata=TRUE, jitter=c(0, 0))

```

```{r paper fig, fig.width=8, fig.height=7}
#windows(8, 7, rescale="fixed")
density.boxplot_gg / reaction.norm + plot_layout(height=c(5, 3)) + plot_annotation(tag_levels="a") & theme(plot.tag=element_text(face="bold"))
#ggsave("fig2.ggplot2_.pdf", width=8, height=7, device=cairo_pdf, unit="in")
```